title: Gatsy's Page
author: Agatha E.O
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science Adventures: Data Insight and visualization; predictive and prescriptive models; informed decision making; Higher Education,
  Sustainability, Institutional and public policy.
theme: minima

# social links
twitter_username: dr_aggie # DO NOT include the @ character, or else the build will fail!
github_username:  gatsy1220 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
